version: "2"
services:

# I have a feeling we can get rid of this, and just use one docker-compose.yml, and just set a ENV var if
# we want dev mode (just gives a docker shell) or not.

  backend:
    build: ./backend/dev-docker
    image: dgtlmoon/changedetection.io:dev
    container_name: changedetection.io-dev
    volumes:
      - ./backend:/app
      - ./requirements.txt:/requirements.txt # Normally COPY'ed in the Dockerfile
      - ./datastore:/datastore

    ports:
      - "127.0.0.1:5001:5000"

    networks:
      - changenet

networks:
  changenet:
