version: '2'
services:
    changedetection.io:
      image: dgtlmoon/changedetection.io
      container_name: changedetection.io
      hostname: changedetection.io
      volumes:
        - changedetection-data:/datastore

  #    environment:
  #        Proxy support example.
  #      - HTTP_PROXY="socks5h://10.10.1.10:1080"
  #      - HTTPS_PROXY="socks5h://10.10.1.10:1080"
  #        An exclude list (useful for notification URLs above) can be specified by with
  #      - NO_PROXY="localhost,192.168.0.0/24"
  #        Base URL of your changedetection.io install (Added to notification alert
  #      - BASE_URL="https://mysite.com"

      ports:
        - 5000:5000
      restart: always

volumes:
  changedetection-data:

