version: "2"
services:

  backend:
    build: .
    image: dgtlmoon/changedetection.io:0.1

    container_name: changedetection.io
    volumes:
      - ./backend:/app
      - ./datastore:/datastore

# autoreload not working :(
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1 #https://stackoverflow.com/questions/58701233/docker-logs-erroneously-appears-empty-until-container-stops
    ports:
      - "127.0.0.1:5000:5000"

    networks:
      - changenet

    restart: always

networks:
  changenet:
