version: "2"
services:

  backend:
    build: ./backend/production-docker
    container_name: changedetection.io
    volumes:
      - ./backend:/app
      - ./datastore:/datastore

    ports:
      - "127.0.0.1:5000:5000"

    networks:
      - changenet

    restart: always

networks:
  changenet:
