services:
  - type: web
    name: changedetection
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python ./changedetection.py -d /datastore -p $PORT
    envVars:
      - key: FETCH_WORKERS
        value: "10"
      # Optional: Add SALTED_PASS in Render dashboard (Environment → Add Secret)
    disk:
      name: changedata
      mountPath: /datastore
      sizeGB: 20

